quarkus:
  log:
    level: INFO
    console:
      format: "%d{HH:mm:ss.SSS} [%t] %-5p %c{36} - %s%e%n"
    category:
      "watchlistarr":
        level: ${LOG_LEVEL:INFO}
  scheduler:
    enabled: true

sonarr:
  bypass-ignored: false
  season-monitoring: "all"

radarr:
  bypass-ignored: false

plex:
  skip-friend-sync: false

delete:
  movie: false
  ended-show: false
  continuing-show: false
  interval-days: 7
  delete-files: true

refresh:
  interval-seconds: 60
